# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_page(object):
    def setupUi(self, login_page):
        login_page.setObjectName("login_page")
        login_page.resize(280, 300)
        login_page.setMinimumSize(QtCore.QSize(280, 300))
        login_page.setMaximumSize(QtCore.QSize(280, 300))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        login_page.setFont(font)
        self.username_box = QtWidgets.QLineEdit(login_page)
        self.username_box.setGeometry(QtCore.QRect(70, 70, 150, 25))
        self.username_box.setObjectName("username_box")
        self.password_box = QtWidgets.QLineEdit(login_page)
        self.password_box.setGeometry(QtCore.QRect(70, 150, 150, 25))
        self.password_box.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_box.setObjectName("password_box")
        self.login_buton = QtWidgets.QPushButton(login_page)
        self.login_buton.setGeometry(QtCore.QRect(110, 210, 75, 25))
        self.login_buton.setObjectName("login_buton")
        self.label = QtWidgets.QLabel(login_page)
        self.label.setGeometry(QtCore.QRect(70, 40, 60, 25))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(login_page)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 60, 25))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(login_page)
        self.label_3.setGeometry(QtCore.QRect(90, 260, 50, 25))
        self.label_3.setObjectName("label_3")
        self.register_button = QtWidgets.QPushButton(login_page)
        self.register_button.setGeometry(QtCore.QRect(150, 260, 40, 25))
        self.register_button.setObjectName("register_button")

        self.retranslateUi(login_page)
        QtCore.QMetaObject.connectSlotsByName(login_page)

    def retranslateUi(self, login_page):
        _translate = QtCore.QCoreApplication.translate
        login_page.setWindowTitle(_translate("login_page", "Login"))
        self.login_buton.setText(_translate("login_page", "Login"))
        self.label.setText(_translate("login_page", "Username"))
        self.label_2.setText(_translate("login_page", "Password"))
        self.label_3.setText(_translate("login_page", "Sign up"))
        self.register_button.setText(_translate("login_page", "Click"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_page = QtWidgets.QWidget()
    ui = Ui_login_page()
    ui.setupUi(login_page)
    login_page.show()
    sys.exit(app.exec_())
