# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_page(object):
    def setupUi(self, register_page):
        register_page.setObjectName("register_page")
        register_page.resize(280, 300)
        register_page.setMinimumSize(QtCore.QSize(280, 300))
        register_page.setMaximumSize(QtCore.QSize(280, 300))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        register_page.setFont(font)
        self.username_box = QtWidgets.QLineEdit(register_page)
        self.username_box.setGeometry(QtCore.QRect(70, 70, 150, 25))
        self.username_box.setObjectName("username_box")
        self.password_box = QtWidgets.QLineEdit(register_page)
        self.password_box.setGeometry(QtCore.QRect(70, 150, 150, 25))
        self.password_box.setObjectName("password_box")
        self.register_button = QtWidgets.QPushButton(register_page)
        self.register_button.setGeometry(QtCore.QRect(110, 210, 75, 25))
        self.register_button.setObjectName("register_button")
        self.label = QtWidgets.QLabel(register_page)
        self.label.setGeometry(QtCore.QRect(70, 40, 60, 25))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(register_page)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 60, 25))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(register_page)
        QtCore.QMetaObject.connectSlotsByName(register_page)

    def retranslateUi(self, register_page):
        _translate = QtCore.QCoreApplication.translate
        register_page.setWindowTitle(_translate("register_page", "Sign Up"))
        self.register_button.setText(_translate("register_page", "Register"))
        self.label.setText(_translate("register_page", "Username"))
        self.label_2.setText(_translate("register_page", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    register_page = QtWidgets.QWidget()
    ui = Ui_register_page()
    ui.setupUi(register_page)
    register_page.show()
    sys.exit(app.exec_())
